// leave off @2x/@3x
const images = {
	logo: require("../Images/ignitenb.png"),
	logoDark: require("../Images/ignitenbdark.png"),
	clearLogo: require("../Images/top_logo.png"),
	appleLogo: require("../Images/apple_logo_white.png"),
	launch: require("../Images/launch-icon.png"),
	ready: require("../Images/your-app.png"),
	ignite: require("../Images/ignite_logo.png"),
	igniteClear: require("../Images/ignite-logo-transparent.png"),
	tileBg: require("../Images/tile_bg.png"),
	background: require("../Images/BG.png"),
	buttonBackground: require("../Images/button-bg.png"),
	api: require("../Images/Icons/icon-api-testing.png"),
	components: require("../Images/Icons/icon-components.png"),
	deviceInfo: require("../Images/Icons/icon-device-information.png"),
	faq: require("../Images/Icons/faq-icon.png"),
	home: require("../Images/Icons/icon-home.png"),
	theme: require("../Images/Icons/icon-theme.png"),
	usageExamples: require("../Images/Icons/icon-usage-examples.png"),
	chevronRight: require("../Images/Icons/chevron-right.png"),
	hamburger: require("../Images/Icons/hamburger.png"),
	backButton: require("../Images/Icons/back-button.png"),
	closeButton: require("../Images/Icons/close-button.png"),
	// fivestar: require("../Images/5-star-rating-new.png"),
	noStar: require("../Images/Star-Ratings/0-star-rating.png"),
	halfStar: require("../Images/Star-Ratings/0.5-star-rating.png"),
	oneStar: require("../Images/Star-Ratings/1-star-rating.png"),
	oneHalfStar: require("../Images/Star-Ratings/1.5-star-rating.png"),
	twoStar: require("../Images/Star-Ratings/2-star-rating.png"),
	twoHalfStar: require("../Images/Star-Ratings/2.5-star-rating.png"),
	threeStar: require("../Images/Star-Ratings/3-star-rating.png"),
	threeHalfStar: require("../Images/Star-Ratings/3.5-star-rating.png"),
	fourStar: require("../Images/Star-Ratings/4-star-rating.png"),
	fourHalfStar: require("../Images/Star-Ratings/4.5-star-rating.png"),
	fiveStar: require("../Images/Star-Ratings/5-star-rating.png"),
	userPhoto: require("../Images/user-profile-default.jpg")
};

export default images;
